name: Daily AI Trend Report Generation

on:
  schedule:
    # 매일 오전 11시 30분 (한국 시간)에 실행 (UTC 02:30)
    # GitHub Actions 스케줄은 UTC 기준입니다.
    # 한국 시간 오전 11시 30분은 UTC 2시 30분과 같습니다.
    - cron: '00 23 * * *'  # 매일 KST 오전 7시 50분에 실행
  workflow_dispatch: # 수동 실행을 위한 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 사용 중인 Python 버전에 맞춰 조정 (예: '3.10')

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run AI Trend Report Generator
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python daily_trend_report.py
